package mensajes;

import java.io.Serializable;

public enum MensajeType implements Serializable{
		MENSAJE_CONEXION,  
		MENSAJE_LISTA_USARIOS, 
		MENSAJE_CERRAR_CONEXION,
		MENSAJE_PEDIR_FICHERO,
		MENSAJE_PREPARADO_CLIENTESERVIDOR,
		MENSAJE_PREPARADO_SERVIDORCLIENTE, 
		MENSAJE_CONFIRMACION_CONEXION,
		MENSAJE_CONFIRMACION_LISTA_USARIOS, 
		MENSAJE_CONFIRMACION_CERRAR_CONEXION, 
		MENSAJE_EMITIR_FICHERO, 
		MENSAJE_ANADIR_FICHERO
	}
